### ISSUE TITLE
breaks growing cotton seeds on everness soils

### ISSUE THREAD

**Issue by programmerjake** [TwigGlenn4/resource_crops#7]
Reproduction:
Start new world based on Minetest Game
enable everness and resource_crops mods
place `everness:dirt_1`
hoe it
place water near it
wait for the soil to become wet
plant cotton seeds on it
observe how the cotton plant quickly breaks -- this is a bug

basically, the replacement farming functions in this mod search specifically for 2 kinds of soil instead of using the specified group like they should:
https://github.com/TwigGlenn4/resource_crops/blob/9b17564e7a068cdc7162baa9038472cc834d5a4b/lib.lua#L66

compare with Minetest Game farming mod:
https://github.com/minetest/minetest_game/blob/77bbcee0cd73ddd2980aadbddb6285550c2735b5/mods/farming/api.lua#L215-L228

**Comment by TwigGlenn4** [comment]
I rewrote a big chunk of the code related to growing crops and published the update as v2.0.0. Now instead of overwriting parts of the `farming` mod I use the API like I probably should have done from the start. In my test world both `farming` crops (wheat, cotton), and resource crops work on `default` and `everness` soil, and theoretically should work on any soil supported by `farming`. I'm going to mark this as closed, but please let me know if you find any bugs I've missed!
